[build]
  command = "gatsby build"
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "gatsby develop -p 9000"
  port = 8888
  targetPort = 9000


[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
